# Template for Streamlit secrets
# Copy this file to secrets.toml and fill in your actual values

# Admin credentials
ADMIN_USERNAME = "your_admin_username"
ADMIN_PASSWORD = "your_secure_password"
DATABASE_PATH = "your_database_path"

# Model URL
MODEL_URL = "your_model_download_url" 
