# Template for Streamlit secrets
# Copy this file to secrets.toml and fill in your actual values

# Admin credentials
ADMIN_USERNAME = "your_admin_username"
ADMIN_PASSWORD = "your_secure_password"
DATABASE_PATH = "your_database_path"

# Model URL
<<<<<<< HEAD
MODEL_URL = "your_model_download_url" 
=======
MODEL_URL = "your_model_download_url" 
>>>>>>> 918c80bd0aefea68d6abc62fcd6fbd1882fb4bbb
